# ----------------------------------------------------------------------------
# Copyright (c) 2021, Diego Garcia Huerta.
#
# Your use of this software as distributed in this GitHub repository, is
# governed by the MIT License
#
# Your use of the Shotgun Pipeline Toolkit is governed by the applicable
# license agreement between you and Autodesk / Shotgun.
#
# The full license is in the file LICENSE, distributed with this software.
# ----------------------------------------------------------------------------


# Author: Diego Garcia Huerta
# Contact: https://www.linkedin.com/in/diegogh/


################################################################################

includes:
- ../app_locations.yml
- ../engine_locations.yml
- ./tk-multi-loader2.yml
- ./tk-multi-publish2.yml
- ./tk-multi-screeningroom.yml
- ./tk-multi-shotgunpanel.yml
- ./tk-multi-snapshot.yml
- ./tk-multi-workfiles2.yml
- ./tk-multi-breakdown.yml
- ./tk-multi-setframerange.yml

################################################################################

# asset
settings.tk-gaffer.asset:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.gaffer.project"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  debug_logging: false
  location: "@engines.tk-gaffer.location"

# asset_step
settings.tk-gaffer.asset_step:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-breakdown: "@settings.tk-multi-breakdown.gaffer"
    tk-multi-loader2: "@settings.tk-multi-loader2.gaffer"
    tk-multi-publish2: "@settings.tk-multi-publish2.gaffer.asset_step"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel"
    tk-multi-snapshot: "@settings.tk-multi-snapshot.gaffer.asset_step"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.gaffer.asset_step"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  - {app_instance: tk-multi-snapshot, name: Snapshot...}
  - {app_instance: tk-multi-workfiles2, name: File Save...}
  - {app_instance: tk-multi-publish2, name: Publish...}
  template_project: asset_work_area_gaffer
  location: "@engines.tk-gaffer.location"

# project
settings.tk-gaffer.project:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.gaffer.project"
    tk-multi-pythonconsole:
      location: '@apps.tk-multi-pythonconsole.location'
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  debug_logging: true
  location: "@engines.tk-gaffer.location"

# sequence
settings.tk-gaffer.sequence:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.gaffer.project"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  location: "@engines.tk-gaffer.location"

# sequence
settings.tk-gaffer.sequence_step:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-breakdown: "@settings.tk-multi-breakdown.gaffer"
    tk-multi-setframerange: "@settings.tk-multi-setframerange.gaffer"
    tk-multi-loader2: "@settings.tk-multi-loader2.gaffer"
    tk-multi-publish2: "@settings.tk-multi-publish2.gaffer.sequence_step"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel"
    tk-multi-snapshot: "@settings.tk-multi-snapshot.gaffer.sequence_step"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.gaffer.sequence_step"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  location: "@engines.tk-gaffer.location"

# shot
settings.tk-gaffer.shot:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.gaffer.project"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  location: "@engines.tk-gaffer.location"

# shot_step
settings.tk-gaffer.shot_step:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-breakdown: "@settings.tk-multi-breakdown.gaffer"
    tk-multi-setframerange: "@settings.tk-multi-setframerange.gaffer"
    tk-multi-loader2: "@settings.tk-multi-loader2.gaffer"
    tk-multi-publish2: "@settings.tk-multi-publish2.gaffer.shot_step"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel.gaffer"
    tk-multi-snapshot: "@settings.tk-multi-snapshot.gaffer.shot_step"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.gaffer.shot_step"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  - {app_instance: tk-multi-snapshot, name: Snapshot...}
  - {app_instance: tk-multi-workfiles2, name: File Save...}
  - {app_instance: tk-multi-publish2, name: Publish...}
  template_project: shot_work_area_gaffer
  location: "@engines.tk-gaffer.location"
