# ----------------------------------------------------------------------------
# Copyright (c) 2021, Diego Garcia Huerta.
#
# Your use of this software as distributed in this GitHub repository, is
# governed by the MIT License
#
# Your use of the Shotgun Pipeline Toolkit is governed by the applicable
# license agreement between you and Autodesk / Shotgun.
#
# The full license is in the file LICENSE, distributed with this software.
# ----------------------------------------------------------------------------


# Author: Diego Garcia Huerta
# Contact: https://www.linkedin.com/in/diegogh/
#
# YOU SHOULD MERGE these entries into your settings file, as
# THIS FILE BY ITSELF WILL NOT WORK
# These are the additions to get the engine up and running with the
# default tk-apps for this environment


################################################################################

# -- gaffer

settings.tk-multi-workfiles2.gaffer.project:
  allow_task_creation: true
  create_new_task_hook: "{self}/create_new_task.py"
  custom_actions_hook: "{self}/custom_actions.py"
  entities:
  - caption: Assets
    entity_type: Task
    filters:
    - [entity, type_is, Asset]
    hierarchy: [entity.Asset.sg_asset_type, entity, step, content]
  - caption: Sequences
    entity_type: Task
    filters:
    - [entity, type_is, Sequence]
    hierarchy: [entity, step, content]
  - caption: Shots
    entity_type: Task
    filters:
    - [entity, type_is, Shot]
    hierarchy: [entity.Shot.sg_sequence, entity, step, content]
  file_extensions: []
  hook_copy_file: "{self}/copy_file.py"
  hook_filter_publishes: default
  hook_filter_work_files: default
  hook_scene_operation: "{engine}/tk-multi-workfiles2/scene_operation_tk-gaffer.py"
  launch_at_startup: false
  my_tasks_extra_display_fields: []
  saveas_default_name: scene
  saveas_prefer_version_up: false
  show_my_tasks: true
  template_publish:
  template_publish_area:
  template_work:
  template_work_area:
  version_compare_ignore_fields: []
  location: "@apps.tk-multi-workfiles2.location"


# asset_step
settings.tk-multi-workfiles2.gaffer.asset_step:
  hook_scene_operation: "{engine}/tk-multi-workfiles2/scene_operation_tk-gaffer.py"
  template_publish: gaffer_asset_publish
  template_publish_area: asset_publish_area_gaffer
  template_work: gaffer_asset_work
  template_work_area: asset_work_area_gaffer
  location: "@apps.tk-multi-workfiles2.location"

# sequence_step
settings.tk-multi-workfiles2.gaffer.sequence_step:
  hook_scene_operation: "{engine}/tk-multi-workfiles2/scene_operation_tk-gaffer.py"
  template_publish: gaffer_sequence_publish
  template_publish_area: sequence_publish_area_gaffer
  template_work: gaffer_sequence_work
  template_work_area: sequence_work_area_gaffer
  location: "@apps.tk-multi-workfiles2.location"

# shot_step
settings.tk-multi-workfiles2.gaffer.shot_step:
  hook_scene_operation: "{engine}/tk-multi-workfiles2/scene_operation_tk-gaffer.py"
  template_publish: gaffer_shot_publish
  template_publish_area: shot_publish_area_gaffer
  template_work: gaffer_shot_work
  template_work_area: shot_work_area_gaffer
  location: "@apps.tk-multi-workfiles2.location"
