# ----------------------------------------------------------------------------
# Copyright (c) 2021, Diego Garcia Huerta.
#
# Your use of this software as distributed in this GitHub repository, is
# governed by the MIT License
#
# Your use of the Shotgun Pipeline Toolkit is governed by the applicable
# license agreement between you and Autodesk / Shotgun.
#
# The full license is in the file LICENSE, distributed with this software.
# ----------------------------------------------------------------------------


# Author: Diego Garcia Huerta
# Contact: https://www.linkedin.com/in/diegogh/
#
# YOU SHOULD MERGE these entries into your settings file, as
# THIS FILE BY ITSELF WILL NOT WORK
# These are the additions to get the engine up and running with the
# default tk-apps for this environment


################################################################################

# ---- Gaffer

# asset step
settings.tk-multi-snapshot.gaffer.asset_step:
  hook_scene_operation: "{engine}/tk-multi-snapshot/scene_operation_tk-gaffer.py"
  template_snapshot: gaffer_asset_snapshot
  template_work: gaffer_asset_work
  hook_thumbnail: "{engine}/thumbnail.py"
  location: "@apps.tk-multi-snapshot.location"

# sequence step
settings.tk-multi-snapshot.gaffer.sequence_step:
  hook_scene_operation: "{engine}/tk-multi-snapshot/scene_operation_tk-gaffer.py"
  template_snapshot: gaffer_sequence_snapshot
  template_work: gaffer_sequence_work
  hook_thumbnail: "{engine}/thumbnail.py"
  location: "@apps.tk-multi-snapshot.location"

# shot step
settings.tk-multi-snapshot.gaffer.shot_step:
  hook_scene_operation: "{engine}/tk-multi-snapshot/scene_operation_tk-gaffer.py"
  template_snapshot: gaffer_shot_snapshot
  template_work: gaffer_shot_work
  hook_thumbnail: "{engine}/thumbnail.py"
  location: "@apps.tk-multi-snapshot.location"
