# ----------------------------------------------------------------------------
# Copyright (c) 2021, Diego Garcia Huerta.
#
# Your use of this software as distributed in this GitHub repository, is
# governed by the MIT License
#
# Your use of the Shotgun Pipeline Toolkit is governed by the applicable
# license agreement between you and Autodesk / Shotgun.
#
# The full license is in the file LICENSE, distributed with this software.
# ----------------------------------------------------------------------------


# Author: Diego Garcia Huerta
# Contact: https://www.linkedin.com/in/diegogh/
#
# YOU SHOULD MERGE these entries into your settings file, as
# THIS FILE BY ITSELF WILL NOT WORK
# These are the additions to get the engine up and running with the
# default tk-apps for this environment
#

# gaffer
settings.tk-multi-loader2.gaffer:
  actions_hook: '{engine}/tk-multi-loader2/tk-gaffer_actions.py'
  action_mappings:
    Alembic Cache: [scene_reader]
    Abc File: [scene_reader]
    VDB File: [scene_reader]
    Lscc File: [scene_reader]
    Scc File: [scene_reader]
    SceneCache: [scene_reader]
    LinkedScene : [scene_reader]
    USD File: [scene_reader]
    USDa File: [scene_reader]
    USDc File: [scene_reader]
    Cache File: [scene_reader]

    # images
    Image: [image_reader]
    Texture: [image_reader]
    Rendered Image: [image_reader]

  entities:
  - caption: Assets
    entity_type: Asset
    filters:
    - [project, is, "{context.project}"]
    hierarchy: [sg_asset_type, code]
  - caption: Shots
    entity_type: Shot
    filters:
    - [project, is, "{context.project}"]
    hierarchy: [sg_sequence, code]
  - caption: My Tasks
    entity_type: Task
    filters:
    - [task_assignees, is, "{context.user}"]
    - [project, is, "{context.project}"]
    hierarchy: [entity, content]
  publish_filters: [["sg_status_list", "is_not", null]]
  location: "@apps.tk-multi-loader2.location"
