# ----------------------------------------------------------------------------
# Copyright (c) 2021, Diego Garcia Huerta.
#
# Your use of this software as distributed in this GitHub repository, is
# governed by the MIT License
#
# Your use of the Shotgun Pipeline Toolkit is governed by the applicable
# license agreement between you and Autodesk / Shotgun.
#
# The full license is in the file LICENSE, distributed with this software.
# ----------------------------------------------------------------------------


# Author: Diego Garcia Huerta
# Contact: https://www.linkedin.com/in/diegogh/
#
# YOU SHOULD MERGE these entries into your template.yml configuration file, as
# THIS FILE BY ITSELF WILL NOT WORK
# These are the additions to the template.yml to get the engine up and
# running with the default tk-apps

keys:
    gaffer.node.name:
        alias: name
        type: str
        filter_by: alphanumeric

    gaffer.image_extension:
        type: str
        alias: extension
        default: png

    gaffer.scene_extension:
        type: str
        alias: extension
        default: scc


paths:
    #
    # gaffer
    #

    # asset
    # define the location of a work area
    asset_work_area_gaffer:
        definition: '@asset_root/work/gaffer'
        root_name: 'primary'
    # define the location of a publish area
    asset_publish_area_gaffer:
        definition: '@asset_root/publish/gaffer'
        root_name: 'primary'

    # The location of WIP files
    gaffer_asset_work:
        definition: '@asset_work_area_gaffer/{name}.v{version}.gfr'
        root_name: 'primary'

    # The location of backups of WIP files
    gaffer_asset_snapshot:
        definition: '@asset_work_area_gaffer/snapshots/{name}.v{version}.{timestamp}.gfr'
        root_name: 'primary'

    gaffer_asset_publish:
        definition: '@asset_publish_area_gaffer/{name}.v{version}.gfr'
        root_name: 'primary'

    gaffer_asset_image_publish:
        definition: '@asset_publish_area_gaffer/images/{name}.v{version}.{gaffer.image_extension}'
        root_name: 'primary'

    gaffer_asset_scene_publish:
        definition: '@asset_publish_area_gaffer/caches/SceneCache/{name}.v{version}.{gaffer.scene_extension}'
        root_name: 'primary'

    # shot
    # define the location of a work area
    shot_work_area_gaffer:
        definition: '@shot_root/work/gaffer'
        root_name: 'primary'
    # define the location of a publish area
    shot_publish_area_gaffer:
        definition: '@shot_root/publish/gaffer'
        root_name: 'primary'
    # The location of WIP files
    gaffer_shot_work:
        definition: '@shot_work_area_gaffer/{name}.v{version}/{name}.v{version}.gfr'
        root_name: 'primary'
    # The location of backups of WIP files
    gaffer_shot_snapshot:
        definition: '@shot_work_area_gaffer/snapshots/{name}.v{version}/{name}.v{version}.{timestamp}.gfr'
        root_name: 'primary'
    # The location of published gaffer files
    gaffer_shot_publish:
        definition: '@shot_publish_area_gaffer/{name}.v{version}/{name}.v{version}.gfr'
        root_name: 'primary'

    gaffer_shot_image_publish:
        definition: '@shot_publish_area_gaffer/images/{name}.v{version}.{gaffer.image_extension}'
        root_name: 'primary'

    gaffer_shot_scene_publish:
        definition: '@shot_publish_area_gaffer/caches/SceneCache/{name}.v{version}.{gaffer.scene_extension}'
        root_name: 'primary'

    # sequence
    # define the location of a work area
    sequence_work_area_gaffer:
        definition: '@sequence_root/work/gaffer'
        root_name: 'primary'
    # define the location of a publish area
    sequence_publish_area_gaffer:
        definition: '@sequence_root/publish/gaffer'
        root_name: 'primary'
    # The location of WIP files
    gaffer_sequence_work:
        definition: '@sequence_work_area_gaffer/{name}.v{version}/{name}.v{version}.gfr'
        root_name: 'primary'
    # The location of backups of WIP files
    gaffer_sequence_snapshot:
        definition: '@sequence_work_area_gaffer/snapsequences/{name}.v{version}/{name}.v{version}.{timestamp}.gfr'
        root_name: 'primary'
    # The location of published gaffer files
    gaffer_sequence_publish:
        definition: '@sequence_publish_area_gaffer/{name}.v{version}/{name}.v{version}.gfr'
        root_name: 'primary'

    gaffer_sequence_image_publish:
        definition: '@sequence_publish_area_gaffer/images/{name}.v{version}.{gaffer.image_extension}'
        root_name: 'primary'

    gaffer_sequence_scene_publish:
        definition: '@sequence_publish_area_gaffer/caches/SceneCache/{name}.v{version}.{gaffer.scene_extension}'
        root_name: 'primary'
